/**
 * Regression test for auto-increment / identity handling in cross-engine DDL.
 *
 * Reproduces the Aiven MySQL → Neon Postgres bug where a MySQL
 * `INT AUTO_INCREMENT PRIMARY KEY` column landed in Postgres as a plain
 * `integer NOT NULL PRIMARY KEY`, leaving the table unable to accept new
 * INSERTs without an explicit id.
 *
 * Pure-DDL check — no live database connection required. Run with:
 *   pnpm --filter api exec tsx scripts/test-auto-increment-ddl.ts
 */
import { buildCreateTable } from '../src/migration/ddl/postgres-ddl.js';
import { buildMysqlCreateTable } from '../src/migration/ddl/mysql-ddl.js';
import type { InferredSchema } from '../src/migration/types.js';

let failed = 0;
function check(name: string, cond: boolean, detail?: string) {
  if (cond) {
    console.log(`  ok   — ${name}`);
  } else {
    failed++;
    console.error(`  FAIL — ${name}${detail ? `\n         ${detail}` : ''}`);
  }
}

// ── MySQL → Postgres ────────────────────────────────────────────────────────
// MySQL reader marks AUTO_INCREMENT columns with autoIncrement: true.
// PG DDL must emit GENERATED BY DEFAULT AS IDENTITY so subsequent INSERTs
// without an explicit id still get a value.
{
  const schema: InferredSchema = {
    namespace: { database: 'app', name: 'users' },
    columns: [
      { name: 'id',    type: 'int',    nullable: false, primaryKey: true, autoIncrement: true },
      { name: 'email', type: 'string', nullable: false },
    ],
    warnings: [],
  };
  const sql = buildCreateTable(schema).join('\n');
  console.log('\n[mysql→pg] CREATE TABLE:\n' + sql);
  check('PG DDL emits GENERATED … AS IDENTITY for auto_increment PK',
    /"id"\s+INTEGER\s+NOT NULL\s+GENERATED BY DEFAULT AS IDENTITY/.test(sql), sql);
  check('PG DDL does NOT include identity on non-AI columns',
    !/"email"[^,]*IDENTITY/.test(sql));
}

// ── Postgres → MySQL ────────────────────────────────────────────────────────
// PG reader marks IDENTITY / SERIAL columns with autoIncrement: true.
// MySQL DDL must emit AUTO_INCREMENT on that column.
{
  const schema: InferredSchema = {
    namespace: { database: 'app', name: 'orders' },
    columns: [
      { name: 'id',     type: 'long',   nullable: false, primaryKey: true, autoIncrement: true },
      { name: 'amount', type: 'decimal', nullable: false },
    ],
    warnings: [],
  };
  const sql = buildMysqlCreateTable(schema).join('\n');
  console.log('\n[pg→mysql] CREATE TABLE:\n' + sql);
  check('MySQL DDL emits AUTO_INCREMENT for identity PK',
    /`id`\s+BIGINT\s+NOT NULL\s+AUTO_INCREMENT/.test(sql), sql);
  check('MySQL DDL does NOT add AUTO_INCREMENT to non-identity column',
    !/`amount`[^,]*AUTO_INCREMENT/.test(sql));
}

// ── Mongo → Postgres ────────────────────────────────────────────────────────
// Mongo inference never sets autoIncrement (the _id is the app's responsibility),
// so the inferred PK should land as a plain integer column — no identity clause.
{
  const schema: InferredSchema = {
    namespace: { database: 'app', name: 'events' },
    columns: [
      { name: 'id',  type: 'int',    nullable: false, primaryKey: true },
      { name: 'tag', type: 'string', nullable: true },
    ],
    warnings: [],
  };
  const sql = buildCreateTable(schema).join('\n');
  console.log('\n[mongo→pg] CREATE TABLE:\n' + sql);
  check('Mongo→PG does NOT add IDENTITY when source had no auto_increment',
    !/IDENTITY/.test(sql), sql);
}

// ── Mongo → MySQL ───────────────────────────────────────────────────────────
{
  const schema: InferredSchema = {
    namespace: { database: 'app', name: 'events' },
    columns: [
      { name: 'id',  type: 'int',    nullable: false, primaryKey: true },
      { name: 'tag', type: 'string', nullable: true },
    ],
    warnings: [],
  };
  const sql = buildMysqlCreateTable(schema).join('\n');
  console.log('\n[mongo→mysql] CREATE TABLE:\n' + sql);
  check('Mongo→MySQL does NOT add AUTO_INCREMENT when source had no auto_increment',
    !/AUTO_INCREMENT/.test(sql), sql);
}

console.log(`\n${failed === 0 ? 'ALL PASS' : `${failed} FAILED`}`);
process.exit(failed === 0 ? 0 : 1);
